### ISSUE TITLE
Change menuName to name to work with react-native-web

### ISSUE THREAD

**Issue by knight33** [instea/react-native-popup-menu#47] opened 2017-10-23 19:29 UTC
when using this with react-native-web, it errors as menuName is not a valid prop.
"warning.js:9 Warning: Unknown prop `menuName` on <div> tag. Remove this prop from the element"

Changing menuName to name inside menu.js, and menuTrigger.js fixes the issue.

**Comment by sodik82** [comment] 2017-10-23 20:47
I am glad to hear that popup-menu is usable on react-native-web....

the problem you are describing might be caused by https://github.com/instea/react-native-popup-menu/blob/master/src/MenuTrigger.js#L16  - `menuName` will get to `others` and than (maybe) lead to warning. Can you try to change it to 
```
const { disabled, onRef, text, children, style, customStyles, menuName, ...other } = this.props;
```
instead of your fix? Please let us know if it helped.

**Comment by knight33** [comment] 2017-10-24 14:18
Yes that did fix it, thanks. 
Things seem to be working well in react-native-web except one other issue
afterSetState = () => this._initOpen(next); never fires on web compile - works on ios compile. I will dig into it and let you Thanks

**Comment by sodik82** [comment] 2017-10-31 22:17
I have fixed 'Unknown prop menuName' in latest release (0.8.4) - thus closing this issue. However if you can come up with good working solution for react-native-web, open PR or another issue

**Closed by sodik82** 2017-10-31 22:17 UTC
