### ISSUE TITLE
React.createElement: type is invalid ---expected a string but got undefined

### ISSUE THREAD

**Issue by kamleshchandnani** [instea/react-native-popup-menu#22] opened 2017-02-06 02:32 UTC
![screenshot from 2017-02-06 08 02 32](https://cloud.githubusercontent.com/assets/11384858/22632840/a73bb26c-ec42-11e6-9582-88a22d2224fc.png)

**Comment by sodik82** [comment] 2017-02-06 08:57
as error suggests, seems there is something wrong with your imports in `ViewLeadDetailsPage`. 

Can you show us what have you added to your component that introduced this error together with your imports?

**Comment by kamleshchandnani** [comment] 2017-02-06 11:03
![screenshot from 2017-02-06 16 24 49](https://cloud.githubusercontent.com/assets/11384858/22644523/fd4e26ee-ec88-11e6-89d0-5159265df566.png)

This is my screen.
Now the header is global navigator.
Each screen is a child pushed by router
````
import React, { Component, Text } from 'react';
import { Container, Header, Title, Button, Icon, Content, Footer, View } from 'native-base';
import HeaderMain from '../components/header';
import FooterMain from '../components/footer';
import ViewLeadDetailsContainer from '../containers/leads/ViewLeadDetailsContainer';
import Menu, {
  MenuContext,
  MenuOptions,
  MenuOption,
  MenuTrigger,
} from 'react-native-popup-menu';
import { StyleSheet } from 'react-native';
let styles = StyleSheet.create({
  button: {
    margin: 10,
  }
})
let globalNavigationObj;
export default class ViewLeadDetailsPage extends Component {
  static route = {
    navigationBar: {
      backgroundColor: '#0096ff',
      tintColor: '#fff',
      title: 'Profile',
      renderLeft: (props) => <Button onPress={() => { globalNavigationObj.pop() }} transparent style={styles.button}>
        <Icon name="md-arrow-back" />
      </Button>,
      renderRight: (props) => <Button transparent style={styles.button}>
        <Icon name="md-more" />
      </Button>,
    }
  }
  constructor(props) {
    super(props);
    globalNavigationObj = this.props.navigator;
  }
  goBack = () => {
    this.props.navigator.pop();
  }
  componentDidMount() {
    console.log('children props ', this.props.children);
  }
  render() {
    return (
      <View>
        <MenuContext style={{ flexDirection: 'column', padding: 30 }}>
          <Menu onSelect={value => alert(`Selected number: ${value}`)} renderer={CustomMenu}>
            <MenuTrigger text="select " />
            <MenuOptions>
              <MenuOption value={1} text='One' />
              <MenuOption value={2}>
                <Text style={{ color: 'red' }}>Two</Text>
              </MenuOption>
              <MenuOption value={3} disabled={true} text='Three' />
            </MenuOptions>
          </Menu>
          <ViewLeadDetailsContainer {...this.props} />
        </MenuContext>
      </View>
    )
  }
}
const CustomMenu = (props) => {
  console.log('herere');
  const { style, children, layouts, ...other } = props;
  const position = { position: 'absolute', top: 0, left: 0 }
  return (
    <View {...other} style={[style, position]}>
      {children}
    </View>
  );
};
```

I want a context menu on the top right when a user clicks a icon.

**Comment by sodik82** [comment] 2017-02-06 12:03
The error seems to be caused by from `Text` import (can't be imported from `react` - use `react-native` instead.

Btw: what kind of navigation do you use?

**Comment by kamleshchandnani** [comment] 2017-02-06 12:06
I use @exponent/Ex-navigation

So i want to associate this open of context menu with the icon in
`renderRight: (props) => <Button transparent style={styles.button}>
        <Icon name="md-more" />
      </Button>`

**Comment by sodik82** [comment] 2017-02-06 12:24
that means that you want something like
```
      renderRight: () => (
          <Menu onSelect={value => alert(`Selected number: ${value}`)}>
            <MenuTrigger>
                 <Icon name="md-more" />
            </MenuTrigger>
            <MenuOptions>
              <MenuOption value={1} text='One' />
            </MenuOptions>
          </Menu>
)
```

however make sure that `MenuContext` is over your "navigation"! Ideally as very first/top element.

**Comment by kamleshchandnani** [comment] 2017-02-06 13:33
https://gist.github.com/kamleshchandnani/43d5e54eacba9d75709198d237904e4d

**Comment by sodik82** [comment] 2017-02-06 14:56
yes, RN has "native" support for context menu that is limited to text entries. This component allows to render icons etc and provides styling options.

**Comment by sodik82** [comment] 2017-02-19 17:52
closing as the original problem was solved.

**Closed by sodik82** 2017-02-19 17:52 UTC
