### ISSUE TITLE
How to close the menu by clicking outside the menu. 

### ISSUE THREAD

**Issue by RukaiJohn** [instea/react-native-popup-menu#141] opened 2018-12-24 04:31 UTC

**Comment by sodik82** [comment] 2019-01-02 12:18
duplicate of #54 ?

**Comment by naorzr** [comment] 2019-01-11 08:54
@sodik82 what if one doesn't use MenuTrigger and instead opens the menu declaratively with the 'opened' attribute on the Menu component.
how can we close the menu by clicking outside of the menu

**Closed** 2019-01-26 19:53 UTC
