### ISSUE TITLE
If onSelect of `<MenuOption>` is not passed, app shows error onSelect is not a fucntion

### ISSUE THREAD

**Issue by sadafk831** [instea/react-native-popup-menu#56] opened 2017-11-26 10:38 UTC
**Issue**
`onSelect` is mandatory to pass to <MenuOption> other wise it gives error.

**Debugged Report**
MenuOption have a Touchable which take onPress which calls this._onSelect(), In _onSelect definition we are doing
````
const { value, onSelect } = this.props;
const shouldClose = onSelect(value) !== false;
````

Here when we don't pass the onSelect to MenuOption second line onSelect gives error `onSelect(value) is not a function`

**Version** 
```
react-native@0.48.4
react-native-popup-menu@0.9.0
```

**Code Snapshot**
```
<Menu onSelect={props.onSelect}>
    <MenuTrigger>{props.children}</MenuTrigger>
    <MenuOptions>
       <MenuOption value=1>One</MenuOption>
    </MenuOptions>
</Menu>
```

**Comment by sodik82** [comment] 2017-11-26 10:48
just to make it clear - when you don't provide `onSelect`, it fails when you click on the `MenuOption`. Am i right? I would assume that it is ok(ish) :)

What would be your expected behaviour or what do you want to achieve?

**Comment by sadafk831** [comment] 2017-11-26 11:51
It actually gives the error and app will not work further if i don't pass the prop,
My expected behaviour is I want to pass onSelect on <Menu> not on <MenuOption> I was using 0.8.0 version initially it was working but as i updated to 0.9.0 it keeps giving me error, `onSelect(value) is not a function`

**Comment by sodik82** [comment] 2017-11-26 11:57
hm... I will check the differences with 0.8 and 0.9. 

how would you expect to happen when you don't provide onSelect (either directly or indirectly) to the menu?

**Comment by sadafk831** [comment] 2017-11-26 15:20
I was passing the onSelect to menu not menuoption with old version, now i am passing it to menuoption

**Comment by sodik82** [comment] 2017-11-26 16:27
here is snack https://snack.expo.io/SJ_MFBOxG ( you can check the code after "closing" QR code popup )

but for a reference:

```
import React, { Component } from 'react';
import { Text, View, StyleSheet } from 'react-native';
import { Constants } from 'expo';
import {
  MenuContext,
  Menu,
  MenuOptions,
  MenuOption,
  MenuTrigger,
} from 'react-native-popup-menu'; // 0.9.0

export default class App extends Component {
  render() {
    return (
      <MenuContext style={styles.container}>
        <View>
          <Menu onSelect={val => alert(val)}>
            <MenuTrigger text="Select action" />
            <MenuOptions>
              <MenuOption value="1">
                <Text>One</Text>
              </MenuOption>
            </MenuOptions>
          </Menu>
        </View>
      </MenuContext>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
  },
});
```

**Comment by sadafk831** [comment] 2017-11-27 11:19
@sodik82 looks similar to my code, In my scenario i am wrapping the main component with the `MenuContext` and created a custom component like follow:

```
const MyMenu = props => (
  <Menu name={props.name} renderer={SlideInMenu}  onSelect={props.onSelect}>
    <MenuTrigger customStyles={triggerStyles}>
      {props.children}
      <MaterialIcon name="keyboard-arrow-down" />
    </MenuTrigger>
    <MenuOptions customStyles={optionsStyles}>
      <ScrollView
        style={[optionsStyles.optionWrapper,
          props.options.length < 7 ? {} : { height: 300 }]}
      >
        {props.options.map((el, idx) => {
          if (typeof el === "object") {
            return (
              <View
                style={subMenu.container}
                key={`${props.name}-item-${el.name}`}
              >
                <View style={subMenu.titleContainer}>
                  {props.selected === el.name &&
                    <MaterialIcon
                      name="check"
                      style={{
                        fontFamily: "proximanova-semibold",
                        fontSize: 20,
                        paddingRight: 8,
                      }}
                    />
                  }
                  <Text
                    style={[subMenu.title,
                      props.selected === el.name ?
                      subMenu.selectedTitle :
                      {},
                    ]}
                  >{el.name}</Text>
                </View>
                <MenuOptions customStyles={subMenu.optionsStyles}  onSelect={el.onSelect}>
                  {el.options.map((op, opidx) =>
                    (<MenuOption key={`${props.name}-item-${el.name}-${opidx}`} value={opidx}>
                      <View style={subMenu.optionsStyles.optionTextContainer}>
                        <MaterialIcon
                          name="note"
                          style={{
                            fontSize: 16,
                          }}
                        />
                        <Text
                          style={[subMenu.optionsStyles.optionText,
                            props.selected === el.name ?
                            subMenu.optionsStyles.selectedOptionText :
                            {},
                          ]}
                        >{op}</Text>
                      </View>
                    </MenuOption>),
                  )}
                </MenuOptions>
              </View>
            );
          }
          return (
            <MenuOption key={`${props.name}-item-${idx}`} value={idx}>
              <View style={optionsStyles.optionTextContainer}>
                {props.options.indexOf(props.selected) === idx &&
                  <MaterialIcon
                    name="check"
                    style={{
                      fontFamily: "proximanova-semibold",
                      fontSize: 20,
                      paddingRight: 8,
                    }}
                  />
                }
                <Text
                  style={[optionsStyles.optionText,
                    props.options.indexOf(props.selected) === idx ?
                    optionsStyles.selectedOptionText :
                    {},
                  ]}
                >{el}</Text>
              </View>
            </MenuOption>
          );
        })}
      </ScrollView>
    </MenuOptions>
  </Menu>
);
```

I render the above component from my header component as follow where `menu is an object passed to my header component.
```
<MyMenu menu={{
 name={menu.name}
 selected={menu.selected}
 options={menu.options}
 onSelect={menu.onSelect}
}} />
```
main menu data object
```
menu = {
  name: "my menu",
  selected: "A",
  options: ["A", "B", "C"],
  onSelect: (id) => console.log(id),
}
```
If we want to make a submenu then we pass the object in options following the structure as menu data object

**Comment by sodik82** [comment] 2017-11-27 13:53
I believe the problem is that your `MenuOption`s are not direct children of `MenuOptions` (due to scrollview)

Please see https://github.com/instea/react-native-popup-menu/issues/45 for ideas how to integrate ScrollView into the menu.

**Comment by sadafk831** [comment] 2017-11-28 10:46
@sodik82 Its almost same as #45 as in my code i have only used scrollview, but this does not change the fact that this is giving the `onSelect(value) is not a function` error after clicking the `menuOption`

**Comment by sodik82** [comment] 2017-11-28 17:20
The thing is that `MenuOptions` pass the `onSelect` to its direct children automatically - therefore either `MenuOption`s must be direct children of `MenuOptions` or your component must ensure the proper propagation. It is not your case - please check #45 in more details.

**Comment by sodik82** [comment] 2017-12-06 16:28
Updating to `0.10.0` might help you ( see https://github.com/instea/react-native-popup-menu/blob/master/doc/examples.md#menu-within-scroll-view )

**Closed** 2017-12-19 17:26 UTC
