### ISSUE TITLE
Adding ScrollView and setting height on scrollview cause menu to pop downward instead pop upward if menu is place at the bottom of screen 

### ISSUE THREAD

**Issue by rajeshlousigam** [instea/react-native-popup-menu#177] opened 2020-02-11 11:04 UTC
If you have question about the usage of the library, please ask question on StackOverflow with tag [react-native-popup-menu](http://stackoverflow.com/questions/tagged/react-native-popup-menu). We are subscribed to it but it also allows community to help you if we are busy.

If you have found a bug, please describe your problem and expected behaviour. Additionally let us know library version, platform on which the problem happens and if possible some code snipets reproducing problem.

**Comment by madox2** [comment] 2020-02-11 14:41
Hi, could you provide us more information about the problem (code sample, screenshot)? The best would be [expo snack](https://snack.expo.io/) which is reproducing the issue.

**Comment by rajeshlousigam** [comment] 2020-02-12 05:55
i got the solution now, i just set the height to be more than it automatically pop upward.
My concern is how do I set manually if i want to show the pop up downward or upward.

**Comment by madox2** [comment] 2020-02-12 10:38
Position in popup menu is automatically computed and there is not property to override it. You can however implement yourself [custom renderer](https://github.com/instea/react-native-popup-menu/blob/master/doc/extensions.md#custom-renderer) where you have positioning of menu under control.
If you are using [popover](https://github.com/instea/react-native-popup-menu/blob/master/doc/api.md#popover), you can force the position of popover through `placement` property.

If you have any other question related to code or usage you can also ask on our [stackoverflow](http://stackoverflow.com/questions/tagged/react-native-popup-menu).

Anyway I am glad that you found solution to the original problem. I am closing this issue because it does not seem to be a real bug.

**Closed by madox2** 2020-02-12 10:38 UTC
